services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      - firestore
    volumes:
      - ./:/app
      - /app/node_modules

  firestore:
    image: mtlynch/firestore-emulator
    ports:
      - "8080:8080"
    environment:
      - FIRESTORE_PROJECT_ID=task-manager
      - FIRESTORE_PORT=8080
